trigger:
  branches:
    include:
    - master
  paths:
    include:
    - databricks-operator/*
    - "*"

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  #ACR_NAME - set this value in AzureDevops variables 
  #AZURE_SUBSCRIPTION - set this value in AzureDevops variables


steps:
- task: AzureCLI@1
  displayName: Push to Azure Container Registry
  inputs:
    azureSubscription: $(AZURE_SUBSCRIPTION)
    scriptLocation: inlineScript 
    inlineScript: az group create --name lols --location eastus

- task: AzureCLI@1
  displayName: Push to Azure Container Registry
  inputs:
    azureSubscription: $(AZURE_SUBSCRIPTION)
    scriptLocation: inlineScript 
    inlineScript: az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 5 --generate-ssh-keys

- task: AzureCLI@1
  displayName: Push to Azure Container Registry
  inputs:
    azureSubscription: $(AZURE_SUBSCRIPTION)
    scriptLocation: inlineScript 
    inlineScript: az aks get-credentials -n myAKSCluster -g myResourceGroup && kubectl apply -f lols.yaml
