[run]
  deadline = "5m"
  skip-files = []

[linters-settings]

  [linters-settings.govet]
    check-shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"
    ignore-words = ["listend", "analyses", "cancelling"]

[linters]
  enable = ["vet", "golint", "gofmt", "deadcode", "varcheck", "structcheck", "misspell", "errcheck", "gosimple", "govet", "ineffassign"]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = []
  
# Example ignore stuff
#  [[issues.exclude-rules]]
#    text = "Error return value of `g.DeleteView` is not checked"
#    linters = ["errcheck"]
#  [[issues.exclude-rules]]
#    text = "Error return value of `g.SetCurrentView` is not checked"
#    linters = ["errcheck"]
#  [[issues.exclude-rules]]
#    text = "Error return value of `*.SetCursor` is not checked"
#    linters = ["errcheck"]