// +build !ignore_autogenerated

/*
Copyright 2019 microsoft.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyMapping) DeepCopyInto(out *KeyMapping) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyMapping.
func (in *KeyMapping) DeepCopy() *KeyMapping {
	if in == nil {
		return nil
	}
	out := new(KeyMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookAdditionalLibrary) DeepCopyInto(out *NotebookAdditionalLibrary) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookAdditionalLibrary.
func (in *NotebookAdditionalLibrary) DeepCopy() *NotebookAdditionalLibrary {
	if in == nil {
		return nil
	}
	out := new(NotebookAdditionalLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookJob) DeepCopyInto(out *NotebookJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookJob.
func (in *NotebookJob) DeepCopy() *NotebookJob {
	if in == nil {
		return nil
	}
	out := new(NotebookJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebookJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookJobList) DeepCopyInto(out *NotebookJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotebookJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookJobList.
func (in *NotebookJobList) DeepCopy() *NotebookJobList {
	if in == nil {
		return nil
	}
	out := new(NotebookJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebookJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookJobSpec) DeepCopyInto(out *NotebookJobSpec) {
	*out = *in
	out.NotebookTask = in.NotebookTask
	if in.NotebookSpec != nil {
		in, out := &in.NotebookSpec, &out.NotebookSpec
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NotebookSpecSecrets != nil {
		in, out := &in.NotebookSpecSecrets, &out.NotebookSpecSecrets
		*out = make([]NotebookSpecSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotebookAdditionalLibraries != nil {
		in, out := &in.NotebookAdditionalLibraries, &out.NotebookAdditionalLibraries
		*out = make([]NotebookAdditionalLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ClusterSpec = in.ClusterSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookJobSpec.
func (in *NotebookJobSpec) DeepCopy() *NotebookJobSpec {
	if in == nil {
		return nil
	}
	out := new(NotebookJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookJobStatus.
func (in *NotebookJobStatus) DeepCopy() *NotebookJobStatus {
	if in == nil {
		return nil
	}
	out := new(NotebookJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookSpecSecret) DeepCopyInto(out *NotebookSpecSecret) {
	*out = *in
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make([]KeyMapping, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookSpecSecret.
func (in *NotebookSpecSecret) DeepCopy() *NotebookSpecSecret {
	if in == nil {
		return nil
	}
	out := new(NotebookSpecSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookStream) DeepCopyInto(out *NotebookStream) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookStream.
func (in *NotebookStream) DeepCopy() *NotebookStream {
	if in == nil {
		return nil
	}
	out := new(NotebookStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookTask) DeepCopyInto(out *NotebookTask) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookTask.
func (in *NotebookTask) DeepCopy() *NotebookTask {
	if in == nil {
		return nil
	}
	out := new(NotebookTask)
	in.DeepCopyInto(out)
	return out
}
