{
 "title": "Databricks Operator",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Reconciliations Per Controller",
   "type": "graph",
   "description": "Total number of reconciliations per controller\n\ncontroller_runtime_reconcile_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(controller_runtime_reconcile_total[1m])",
     "legendFormat": "{{controller}} - {{result}}"
    }
   ]
  },
  {
   "title": "Average Databricks Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(databricks_request_duration_seconds_bucket[1m])) by (action, object_type, le)) * 1e3",
     "legendFormat": " {{object_type}} - {{action}} Avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(databricks_request_duration_seconds_bucket[1m])) by (action, object_type, le)) * 1e3",
     "legendFormat": " {{object_type}} - {{action}} 95%"
    }
   ]
  },
  {
   "title": "Controller Reconcile Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(controller_runtime_reconcile_time_seconds_bucket[1m])) by (le, controller))",
     "legendFormat": "{{controller}} - Avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket[1m])) by (le, controller))",
     "legendFormat": "{{controller}} - 95%"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum[1m])) / sum(rate(controller_runtime_reconcile_time_seconds_count[1m])) ",
     "legendFormat": "{{controller}} - Mean"
    }
   ]
  },
  {
   "title": "Databricks REST endpoint calls - Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": " increase(databricks_request_duration_seconds_bucket{outcome=\"success\"}[1m])",
     "legendFormat": "{{object_type}} - {{action}}"
    }
   ]
  },
  {
   "title": "Workqueue Adds",
   "type": "graph",
   "description": "Total number of adds handled by workqueue\n\nworkqueue_adds_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Ops" }
   ],
   "targets": [
    {
     "expr": "increase(workqueue_adds_total{name=~\"run|djob|dcluster|dbfsblock|secretscope|workspaceitem\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Databricks REST endpoint calls - Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": " increase(databricks_request_duration_seconds_bucket{outcome=\"failure\"}[1m])",
     "legendFormat": "{{object_type}} - {{action}} "
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "graph",
   "description": "Current depth of workqueue\n\nworkqueue_depth",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{name=~\"run|djob|dcluster|dbfsblock|secretscope|workspaceitem\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue - Work Duration",
   "type": "graph",
   "description": "How long in seconds processing an item from workqueue takes\n\n(workqueue_work_duration_seconds)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "  histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{name=~\"run|djob|dcluster|dbfsblock|secretscope|workspaceitem\"}[1m])) by (le, name))",
     "legendFormat": "{{name}} - Avg"
    },
    {
     "expr": "  histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket{name=~\"run|djob|dcluster|dbfsblock|secretscope|workspaceitem\"}[1m])) by (le, name))",
     "legendFormat": "{{name}} - 95%"
    }
   ]
  },
  {
   "title": "Workqueue - Queue Duration",
   "type": "graph",
   "description": "How long in seconds an item stays in workqueue before being requested (workqueue_queue_duration_seconds)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{name=~\"run|djob|dcluster|dbfsblock|secretscope|workspaceitem\"}[1m])) by (le, name))",
     "legendFormat": "{{name}} - AVG"
    },
    {
     "expr": " histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{name=~\"run|djob|dcluster|dbfsblock|secretscope|workspaceitem\"}[1m])) by (le, name))",
     "legendFormat": "{{name}} - 95%"
    }
   ]
  }
 ]
}