{
 "title": "Databricks Mock API",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response time (mean)",
   "type": "graph",
   "description": "Mean response times for calls to the mock API",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(databricks_mock_api_response_time_sum[1m]) / rate(databricks_mock_api_response_time_count[1m])",
     "legendFormat": "{{type}} - {{action}}"
    }
   ]
  },
  {
   "title": "Response time (percentiles)",
   "type": "graph",
   "description": "Response time percentiles for calls to mock API",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(databricks_mock_api_response_time_bucket[1m])) by (le, action, type))",
     "legendFormat": "{{type}} - {{action}} - P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(databricks_mock_api_response_time_bucket[1m])) by (le, action, type))",
     "legendFormat": "{{type}} - {{action}} -  P95"
    }
   ]
  },
  {
   "title": "Incoming requests (RPS)",
   "type": "graph",
   "description": "Rate of requests to the mock API (requests per second)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(databricks_mock_api_response_time_count[1m])) by (type, action, code)",
     "legendFormat": "{{type}} - {{action}} - {{code}}"
    },
    {
     "expr": "sum(rate(databricks_mock_api_response_time_count[1m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "Incoming requests (Total)",
   "type": "graph",
   "description": "Total number of requests to the mock API",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "databricks_mock_api_response_time_count",
     "legendFormat": "{{type}} - {{action}} - {{code}}"
    },
    {
     "expr": "sum(databricks_mock_api_response_time_count)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(databricks_mock_api_response_time_count{code!=\"200\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(databricks_mock_api_response_time_count{code!=\"200\"}[1m])) by (type, action, code)",
     "legendFormat": "{{type}} - {{action}} - {{code}}"
    }
   ]
  }
 ]
}