# permissions for end users to edit secretscopes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretscope-editor-role
rules:
- apiGroups:
  - databricks.microsoft.com
  resources:
  - secretscopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - secretscopes/status
  verbs:
  - get
