# permissions for end users to view secretscopes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretscope-viewer-role
rules:
- apiGroups:
  - databricks.microsoft.com
  resources:
  - secretscopes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - secretscopes/status
  verbs:
  - get
