/*
 * Databricks Controller
 *
 * Manage Databricks
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateJobStatus struct {
	// The name identifier of a job run
	RunName string            `json:"run_name"`
	Result  []CreateJobResult `json:"result,omitempty"`
}
