/*
 * Databricks Controller
 *
 * Manage Databricks
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NotebookTask struct {
	NotebookPath string `json:"notebook_path,omitempty"`
}
