/*
 * Databricks Controller
 *
 * Manage Databricks
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RunDefinition struct {
	// The name identifier of a job run
	RunName                     string      `json:"run_name"`
	NotebookSpecSecrets         interface{} `json:"notebook_spec_secrets,omitempty"`
	NotebookSpec                interface{} `json:"notebook_spec,omitempty"`
	NotebookAdditionalLibraries interface{} `json:"notebook_additional_libraries,omitempty"`
	NewCluster                  *NewCluster `json:"new_cluster,omitempty"`
	// timeout in seconds
	TimeoutSeconds int32         `json:"timeout_seconds,omitempty"`
	NotebookTask   *NotebookTask `json:"notebook_task,omitempty"`
}
