/*
 * Databricks Controller
 *
 * Manage Databricks
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterSpec struct {
	NewCluster []NewCluster  `json:"new_cluster,omitempty"`
	Libraries  []interface{} `json:"libraries,omitempty"`
}
