/*
 * Databricks Controller
 *
 * Manage Databricks
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Run struct {
	JobId             int32             `json:"job_id,omitempty"`
	RunId             int32             `json:"run_id,omitempty"`
	NumberInJob       int32             `json:"number_in_job,omitempty"`
	Task              *interface{}      `json:"task,omitempty"`
	ClusterSpec       []ClusterSpec     `json:"cluster_spec,omitempty"`
	State             []State           `json:"state,omitempty"`
	ClusterInstance   []ClusterInstance `json:"cluster_instance,omitempty"`
	StartTime         *interface{}      `json:"start_time,omitempty"`
	SetupDuration     int32             `json:"setup_duration,omitempty"`
	ExecutionDuration int32             `json:"execution_duration,omitempty"`
	CleanupDuration   int32             `json:"cleanup_duration,omitempty"`
	CreatorUserName   string            `json:"creator_user_name,omitempty"`
	RunName           string            `json:"run_name,omitempty"`
	RunPageUrl        string            `json:"run_page_url,omitempty"`
	RunType           string            `json:"run_type,omitempty"`
}
