/*
 * Databricks Controller
 *
 * Manage Databricks
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type State struct {
	LifeCycleState string `json:"life_cycle_state,omitempty"`
	ResultState    string `json:"result_state,omitempty"`
	StateMessage   string `json:"state_message,omitempty"`
}
