apiVersion: databricks.microsoft.com/v1beta1
kind: SecretScope
metadata:
  name: secretscope-sample
spec:
  initial_manage_principal: users
  secrets:
    - key: string-secret
      string_value: helloworld
    - key: byte-secret
      byte_value: aGVsbG93b3JsZA==
    - key: secret-key2
      value_from:
        secret_key_ref:
          name: mysecret
          key: username
  acls:
    - principal: jacob.zhou@dataexchange.work
      permission: READ
