apiVersion: databricks.microsoft.com/v1
kind: NotebookJob
metadata:
  annotations:
    microsoft.k8s.io/author: azkhojan@microsoft.com
  name: sample1run1
spec:
  notebookTask:
    notebookPath: "/test-notebook"
  timeoutSeconds: 500
  notebookSpec:
    "flag": "true"
  notebookSpecSecrets:
    - secretName: "test-secret"
      mapping :
        - "secretKey": "my_secret_key"
          "outputKey": "dbricks_secret_key"
  notebookAdditionalLibraries:
    - type: "maven"
      properties:
        coordinates: "com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.9"
  clusterSpec:
    sparkVersion: "5.2.x-scala2.11"
    nodeTypeId: "Standard_DS12_v2"
    numWorkers: 1
