apiVersion: databricks.microsoft.com/v1alpha1
kind: Djob
metadata:
  name: djob-sample-1
spec:
  # This spec is directly linked to the JobSettings structure
  # https://docs.databricks.com/api/latest/jobs.html#jobsettings
  new_cluster:
    spark_version: 5.3.x-scala2.11
    node_type_id: Standard_D3_v2
    num_workers: 10
  # libraries:
    # # - jar: 'dbfs:/my-jar.jar'
    # - maven:
        # coordinates: 'org.jsoup:jsoup:1.7.2'
  timeout_seconds: 3600
  max_retries: 4
  schedule:
    quartz_cron_expression: 0 15 22 ? * *
    timezone_id: America/Los_Angeles
  notebook_task:
    notebook_path: /Users/amr.asem@dataexchange.work/djob_run_test_amr_clone
    base_parameters: {}
