apiVersion: v1
kind: Namespace
metadata:
  name: locust
---
apiVersion: batch/v1
kind: Job
metadata:
  name: locust-loadtest
  namespace: locust
  labels:
    app: locust-loadtest
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        app: locust-loadtest
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: control-plane
                  operator: In
                  values:
                  - controller-manager
            topologyKey: kubernetes.io/hostname
            namespaces:
              - azure-databricks-operator-system
              - default
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - databricks-mock-api
            topologyKey: kubernetes.io/hostname
            namespaces:
              - azure-databricks-operator-system
              - default
      containers:
      - name: loadtestrunner
        image: locust:latest
        command: ['locust', '-f', 'behaviours/scenario1_run_submit_delete.py']
        ports:
        - containerPort: 8089
          name: webui
        - containerPort: 9090
          name: metrics
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: locust-loadtest
  namespace: locust
  labels:
    app: locust-loadtest
spec:
  ports:
  - port: 8089
    protocol: TCP
    name: webui
  - port: 9090
    protocol: TCP
    name: metrics
  selector:
    app: locust-loadtest
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: locust-loadtest-servicemonitor
  namespace: locust
  labels:
    app: locust-loadtest
spec:
  selector:
    matchLabels:
      app: locust-loadtest
  namespaceSelector:
    matchNames:
      - locust 
  endpoints:
  - port: metrics
    path: /
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: locust-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: locust
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
