
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: workspaceitems.databricks.microsoft.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.object_hash
    name: SHA1SUM
    type: string
  - JSONPath: .status.object_info.language
    name: Language
    type: string
  - JSONPath: .status.object_info.object_type
    name: Type
    priority: 1
    type: string
  - JSONPath: .status.object_info.path
    name: Path
    priority: 1
    type: string
  group: databricks.microsoft.com
  names:
    kind: WorkspaceItem
    plural: workspaceitems
  scope: ""
  subresources: {}
  validation:
    openAPIV3Schema:
      description: WorkspaceItem is the Schema for the workspaceitems API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WorkspaceItemSpec defines the desired state of WorkspaceItem
          properties:
            content:
              type: string
            format:
              type: string
            language:
              type: string
            path:
              type: string
          type: object
        status:
          description: WorkspaceItemStatus defines the observed state of WorkspaceItem
          properties:
            object_hash:
              type: string
            object_info:
              properties:
                language:
                  type: string
                object_type:
                  type: string
                path:
                  type: string
              type: object
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
