
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: secretscopes.databricks.microsoft.com
spec:
  group: databricks.microsoft.com
  names:
    kind: SecretScope
    plural: secretscopes
  scope: ""
  validation:
    openAPIV3Schema:
      description: SecretScope is the Schema for the secretscopes API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SecretScopeSpec defines the desired state of SecretScope
          properties:
            acls:
              items:
                properties:
                  permission:
                    type: string
                  principal:
                    type: string
                type: object
              type: array
            initial_manage_permission:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: string
            secrets:
              items:
                properties:
                  byte_value:
                    type: string
                  key:
                    type: string
                  string_value:
                    type: string
                  value_from:
                    properties:
                      secret_key_ref:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        type: object
                    type: object
                type: object
              type: array
          type: object
        status:
          description: SecretScopeStatus defines the observed state of SecretScope
          properties:
            secretscope:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              properties:
                backend_type:
                  type: string
                name:
                  type: string
              type: object
          type: object
      type: object
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
