
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: dbfsblocks.databricks.microsoft.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.file_hash
    name: SHA1SUM
    type: string
  - JSONPath: .status.file_info.path
    name: Path
    type: string
  - JSONPath: .status.file_info.file_size
    name: Size
    type: integer
  group: databricks.microsoft.com
  names:
    kind: DbfsBlock
    plural: dbfsblocks
  scope: ""
  subresources: {}
  validation:
    openAPIV3Schema:
      description: DbfsBlock is the Schema for the dbfsblocks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DbfsBlockSpec defines the desired state of DbfsBlock
          properties:
            data:
              type: string
            path:
              type: string
          type: object
        status:
          description: DbfsBlockStatus defines the observed state of DbfsBlock
          properties:
            file_hash:
              type: string
            file_info:
              properties:
                file_size:
                  format: int64
                  type: integer
                is_dir:
                  type: boolean
                path:
                  type: string
              type: object
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
